/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab7p2_jafetmorel;

import java.util.ArrayList;
import java.util.logging.Level;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 24661
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        /*adminNav an = new adminNav("./naves.cbm");
        an.cargarArchivo();
        DefaultComboBoxModel model = (DefaultComboBoxModel) cb_nave.getModel();
        for (int i = 0; i < an.getListaNav().size(); i++) {
            model.addElement(an.getListaNav().get(i));
        }
        cb_nave.setModel(model);
        an.escribirArchivo();

        adminDes ad = new adminDes("./destinos.cbm");
        ad.cargarArchivo();
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_dest.getModel();
        for (int i = 0; i < ad.getListaDes().size(); i++) {
            modelo.addElement(ad.getListaDes().get(i));
        }
        cb_dest.setModel(modelo);
        ad.escribirArchivo();

        adminAst aa = new adminAst("./astronautas.cbm");
        aa.cargarArchivo();
        DefaultListModel lista = (DefaultListModel) jList1.getModel();
        for (int i = 0; i < aa.getListaAst().size(); i++) {
            lista.addElement(aa.getListaAst().get(i));
        }
        jList1.setModel(lista);
        aa.escribirArchivo();*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jProgressBar1 = new javax.swing.JProgressBar();
        jProgressBar2 = new javax.swing.JProgressBar();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        Simulación = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        cb_nave = new javax.swing.JComboBox<>();
        cb_dest = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tf_idast = new javax.swing.JTextField();
        tf_nomast = new javax.swing.JTextField();
        tf_apellido = new javax.swing.JTextField();
        tf_nacionalidad = new javax.swing.JTextField();
        tf_titulo = new javax.swing.JTextField();
        tf_context = new javax.swing.JTextField();
        sp_peso = new javax.swing.JSpinner();
        jb_ast = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        tf_nomnav = new javax.swing.JTextField();
        tf_idnav = new javax.swing.JTextField();
        sp_pers = new javax.swing.JSpinner();
        sp_desp = new javax.swing.JSpinner();
        sp_aterr = new javax.swing.JSpinner();
        sp_vel = new javax.swing.JSpinner();
        sp_cons = new javax.swing.JSpinner();
        sp_distancia = new javax.swing.JSpinner();
        sp_prin = new javax.swing.JSpinner();
        sp_res = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        tf_desnom = new javax.swing.JTextField();
        tf_des = new javax.swing.JTextField();
        cb_tipo = new javax.swing.JComboBox<>();
        sp_ox = new javax.swing.JSpinner();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_ast = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_nav = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        table_des = new javax.swing.JTable();

        jLabel26.setText("Tanque principal");

        jLabel27.setText("Tanque reserva");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27)
                    .addComponent(jLabel26)
                    .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                        .addComponent(jProgressBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(172, Short.MAX_VALUE))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(115, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Simulación.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SimulaciónStateChanged(evt);
            }
        });

        jLabel22.setText("Nave");

        jLabel23.setText("Destino");

        jList1.setModel(new DefaultListModel());
        jScrollPane4.setViewportView(jList1);

        jLabel24.setText("Lista de todos los Astronautas");

        jLabel25.setText("Lista de astronautas que iran a la misión:");

        jList2.setModel(new DefaultListModel());
        jScrollPane5.setViewportView(jList2);

        jButton3.setText("Enlistar astronauta para la misión");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Iniciar simulación");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(cb_nave, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(78, 78, 78)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(cb_dest, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(jLabel25))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 159, Short.MAX_VALUE)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jButton3)))
                .addGap(51, 51, 51))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_nave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_dest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                            .addComponent(jScrollPane4)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        Simulación.addTab("Simulación", jPanel1);

        jLabel1.setText("ID");

        jLabel2.setText("Nombre");

        jLabel3.setText("Apellido");

        jLabel4.setText("Nacionalidad");

        jLabel5.setText("Título universitario");

        jLabel6.setText("Contextura física");

        jLabel7.setText("Peso");

        sp_peso.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        sp_peso.setEditor(new javax.swing.JSpinner.NumberEditor(sp_peso, ""));

        jb_ast.setText("Agregar Astronauta");
        jb_ast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_astActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_nacionalidad)
                    .addComponent(tf_titulo)
                    .addComponent(tf_context)
                    .addComponent(sp_peso)
                    .addComponent(tf_idast, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_nomast)
                    .addComponent(tf_apellido))
                .addGap(327, 327, 327))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(jb_ast)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf_idast, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_nomast, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_nacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tf_context, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(sp_peso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jb_ast)
                .addContainerGap(168, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Astronautas", jPanel4);

        jLabel8.setText("Nombre");

        jLabel9.setText("Identificador");

        jLabel10.setText("Cantidad máxima de personas");

        jLabel11.setText("Tiempo de despegue (seg)");

        jLabel12.setText("Tiempo de aterrizaje (seg)");

        jLabel13.setText("Velocidad a la que viaja (km/h)");

        jLabel14.setText("Distancia máxima que puede viajar (km)");

        jLabel15.setText("Cantidad de combustible que se consume (km/L)");

        jLabel16.setText("Cantidad de combustible en tanque principal (L)");

        jLabel17.setText("Cantidad de combustible en tanque de reserva (L)");

        sp_pers.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        sp_desp.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        sp_aterr.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        sp_vel.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        sp_cons.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        sp_distancia.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        sp_prin.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        sp_res.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jButton1.setText("Agregar nave");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addComponent(jLabel17)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf_nomnav)
                    .addComponent(tf_idnav)
                    .addComponent(sp_pers, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(sp_desp)
                    .addComponent(sp_aterr)
                    .addComponent(sp_vel)
                    .addComponent(sp_distancia)
                    .addComponent(sp_cons)
                    .addComponent(sp_prin)
                    .addComponent(sp_res))
                .addContainerGap(466, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tf_nomnav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tf_idnav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(sp_pers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(sp_desp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(sp_aterr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(sp_vel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(sp_distancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(sp_cons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(sp_prin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(sp_res, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Naves", jPanel5);

        jLabel18.setText("Nombre");

        jLabel19.setText("Distancia entre destino y la tierra(km)");

        jLabel20.setText("Tipo de superficie");

        jLabel21.setText("Saturación de oxígeno");

        cb_tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rocosa", "Líquida", "Gasesosa" }));

        sp_ox.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));

        jButton2.setText("Agregar Destino");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel21)
                    .addComponent(jLabel20)
                    .addComponent(jLabel19)
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf_desnom)
                    .addComponent(tf_des)
                    .addComponent(cb_tipo, 0, 100, Short.MAX_VALUE)
                    .addComponent(sp_ox))
                .addContainerGap(536, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(182, 182, 182))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(tf_desnom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(tf_des, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(cb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(sp_ox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jButton2)
                .addContainerGap(287, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Destino", jPanel6);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );

        Simulación.addTab("Agregar", jPanel2);

        jTabbedPane3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane3StateChanged(evt);
            }
        });

        table_ast.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Apellido", "Nacionalidad", "Título", "Contextura", "Peso", "Cantidad de misiones"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table_ast);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 858, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(263, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Astronautas", jPanel7);

        table_nav.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Identificador", "Máxima personas", "Tiempo de despegue", "Tiempo de aterrizaje", "Velocidad", "Distancia", "Combustible", "Tanque principal", "Tanque reserva"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(table_nav);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 858, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(304, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Naves", jPanel8);

        table_des.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Distancia", "Superficie", "Saturación de oxígeno"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(table_des);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 858, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(329, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Destino", jPanel9);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane3)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane3)
                .addContainerGap())
        );

        Simulación.addTab("Listar", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Simulación)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Simulación)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_astActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_astActionPerformed
        // TODO add your handling code here:
        adminAst aa = new adminAst("./astronautas.cbm");
        aa.cargarArchivo();
        aa.setAst(new Astronautas(Integer.parseInt(tf_idast.getText()), tf_nomast.getText(), tf_apellido.getText(), tf_nacionalidad.getText(), tf_titulo.getText(), tf_context.getText(), (int) sp_peso.getValue()));
        aa.escribirArchivo();
        tf_idast.setText("");
        tf_nomast.setText("");
        tf_apellido.setText("");
        tf_nacionalidad.setText("");
        tf_titulo.setText("");
        tf_context.setText("");
        sp_peso.setValue(0);
    }//GEN-LAST:event_jb_astActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        adminNav an = new adminNav("./naves.cbm");
        an.cargarArchivo();
        an.setNav(new Naves(tf_nomnav.getText(), tf_idnav.getText(), (int) sp_pers.getValue(), (int) sp_desp.getValue(), (int) sp_aterr.getValue(), (int) sp_vel.getValue(), (int) sp_distancia.getValue(), (int) sp_cons.getValue(), (int) sp_prin.getValue(), (int) sp_res.getValue()));
        an.escribirArchivo();
        tf_nomnav.setText("");
        tf_idnav.setText("");
        sp_pers.setValue(0);
        sp_desp.setValue(0);
        sp_aterr.setValue(0);
        sp_vel.setValue(0);
        sp_distancia.setValue(0);
        sp_cons.setValue(0);
        sp_prin.setValue(0);
        sp_res.setValue(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        adminDes ad = new adminDes("./destinos.cbm");
        ad.cargarArchivo();
        String tipo = "";
        if (cb_tipo.getSelectedIndex() == 0) {
            tipo = "Rocosa";
        } else if (cb_tipo.getSelectedIndex() == 1) {
            tipo = "Líquido";
        } else if (cb_tipo.getSelectedIndex() == 2) {
            tipo = "Gaseosa";
        }
        ad.setDes(new Destino(tf_desnom.getText(), Integer.parseInt(tf_des.getText()), tipo, (int) sp_ox.getValue()));
        ad.escribirArchivo();
        cb_tipo.setSelectedIndex(0);
        tf_des.setText("");
        sp_ox.setValue(0);
        tf_desnom.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTabbedPane3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane3StateChanged
        // TODO add your handling code here:
        if (jTabbedPane3.getSelectedIndex() == 0) {
            DefaultTableModel model = (DefaultTableModel) table_ast.getModel();
            model.setRowCount(0);
            adminAst aa = new adminAst("./astronautas.cbm");
            aa.cargarArchivo();
            for (int i = 0; i < aa.getListaAst().size(); i++) {
                Object[] row = {aa.getListaAst().get(i).getId(), aa.getListaAst().get(i).getNombre(), aa.getListaAst().get(i).getApellido(), aa.getListaAst().get(i).getNacionalidad(), aa.getListaAst().get(i).getTitun(), aa.getListaAst().get(i).getContext(), aa.getListaAst().get(i).getPeso(), aa.getListaAst().get(i).getMisiones()};
                model.addRow(row);
            }
            table_ast.setModel(model);
            aa.escribirArchivo();
        } else if (jTabbedPane3.getSelectedIndex() == 1) {
            DefaultTableModel model = (DefaultTableModel) table_nav.getModel();
            model.setRowCount(0);
            adminNav an = new adminNav("./naves.cbm");
            an.cargarArchivo();
            for (int i = 0; i < an.getListaNav().size(); i++) {
                Object[] row = {an.getListaNav().get(i).getNombre(), an.getListaNav().get(i).getIden(), an.getListaNav().get(i).getMaxcant(), an.getListaNav().get(i).getDespegue(), an.getListaNav().get(i).getAterrizaje(), an.getListaNav().get(i).getVeloc(), an.getListaNav().get(i).getMaxdist(), an.getListaNav().get(i).getGasto(), an.getListaNav().get(i).getCombprin(), an.getListaNav().get(i).getCombres()};
                model.addRow(row);
            }
            table_nav.setModel(model);
            an.escribirArchivo();
        } else if (jTabbedPane3.getSelectedIndex() == 2) {
            DefaultTableModel model = (DefaultTableModel) table_des.getModel();
            model.setRowCount(0);
            adminDes ad = new adminDes("./destinos.cbm");
            ad.cargarArchivo();
            for (int i = 0; i < ad.getListaDes().size(); i++) {
                Object[] row = {ad.getListaDes().get(i).getNombre(), ad.getListaDes().get(i).getDistancia(), ad.getListaDes().get(i).getSuperficie(), ad.getListaDes().get(i).getSaturacion()};
                model.addRow(row);
            }
            table_des.setModel(model);
            ad.escribirArchivo();
        }
    }//GEN-LAST:event_jTabbedPane3StateChanged

    private void SimulaciónStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SimulaciónStateChanged
        // TODO add your handling code here:
        if (Simulación.getSelectedIndex() == 0) {
            adminNav an = new adminNav("./naves.cbm");
            an.cargarArchivo();
            DefaultComboBoxModel model = new DefaultComboBoxModel();
            for (int i = 0; i < an.getListaNav().size(); i++) {
                model.addElement(an.getListaNav().get(i));
            }
            cb_nave.setModel(model);
            an.escribirArchivo();
            adminDes ad = new adminDes("./destinos.cbm");
            ad.cargarArchivo();
            DefaultComboBoxModel modelo = new DefaultComboBoxModel();
            for (int i = 0; i < ad.getListaDes().size(); i++) {
                modelo.addElement(ad.getListaDes().get(i));
            }
            cb_dest.setModel(modelo);
            ad.escribirArchivo();

            adminAst aa = new adminAst("./astronautas.cbm");
            aa.cargarArchivo();
            DefaultListModel lista = new DefaultListModel();
            for (int i = 0; i < aa.getListaAst().size(); i++) {
                lista.addElement(aa.getListaAst().get(i));
            }
            jList1.setModel(lista);
            aa.escribirArchivo();
        }
    }//GEN-LAST:event_SimulaciónStateChanged

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        DefaultListModel modelo = (DefaultListModel) jList2.getModel();
        DefaultListModel m = (DefaultListModel) jList1.getModel();
        modelo.addElement((Astronautas) m.get(jList1.getSelectedIndex()));
        jList2.setModel(modelo);
        a.add((Astronautas) m.get(jList1.getSelectedIndex()));
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        boolean fis = false, astr = false, ing = false;
        for (int i = 0; i < a.size(); i++) {
            if (a.get(i).getTitun().equalsIgnoreCase("Ingeniero")) {
                ing = true;
            } else if (a.get(i).getTitun().equalsIgnoreCase("Fisico")) {
                fis = true;
            } else if (a.get(i).getTitun().equalsIgnoreCase("Astrofisico")) {
                astr = true;
            }
        }
        Naves n = (Naves) cb_nave.getSelectedItem();
        Destino d = (Destino) cb_dest.getSelectedItem();
        boolean max = false;
        if (n.getMaxcant() <= a.size()) {
            max = true;
        }
        if (fis & astr & ing & max) {
            jProgressBar1.setValue(n.getCombprin());
            jProgressBar2.setValue(n.getCombres());
            int dis = d.getDistancia();
            while (jProgressBar1.getValue() >= 0 || dis > 0) {
                try {
                    Thread.sleep(5000);
                    int x = (int) jProgressBar1.getValue();
                    dis = dis - (n.getVeloc() * n.getGasto());
                    int y = x - (dis - n.getVeloc() * n.getGasto());
                    jProgressBar1.setValue(y);
                    jProgressBar1.repaint();
                } catch (InterruptedException ex) {

                }
                while (jProgressBar2.getValue() >= 0 || dis > 0) {
                    try {
                        Thread.sleep(5000);
                        int x = (int) jProgressBar2.getValue();
                        dis = dis - (n.getVeloc() * n.getGasto());
                        int y = x - (dis - n.getVeloc() * n.getGasto());
                        jProgressBar2.setValue(y);
                        jProgressBar2.repaint();
                    } catch (InterruptedException ex) {

                    }

                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "La tripulación debe ser menor o igual a la cantidad máxima de pasajeros de la nave. También se debe llevar un Fisico, Astrofisico e ingeniero. Para mas sobre astronautas y naves vaya a la pestaña de listar.");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Simulación;
    private javax.swing.JComboBox<String> cb_dest;
    private javax.swing.JComboBox<String> cb_nave;
    private javax.swing.JComboBox<String> cb_tipo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JButton jb_ast;
    private javax.swing.JSpinner sp_aterr;
    private javax.swing.JSpinner sp_cons;
    private javax.swing.JSpinner sp_desp;
    private javax.swing.JSpinner sp_distancia;
    private javax.swing.JSpinner sp_ox;
    private javax.swing.JSpinner sp_pers;
    private javax.swing.JSpinner sp_peso;
    private javax.swing.JSpinner sp_prin;
    private javax.swing.JSpinner sp_res;
    private javax.swing.JSpinner sp_vel;
    private javax.swing.JTable table_ast;
    private javax.swing.JTable table_des;
    private javax.swing.JTable table_nav;
    private javax.swing.JTextField tf_apellido;
    private javax.swing.JTextField tf_context;
    private javax.swing.JTextField tf_des;
    private javax.swing.JTextField tf_desnom;
    private javax.swing.JTextField tf_idast;
    private javax.swing.JTextField tf_idnav;
    private javax.swing.JTextField tf_nacionalidad;
    private javax.swing.JTextField tf_nomast;
    private javax.swing.JTextField tf_nomnav;
    private javax.swing.JTextField tf_titulo;
    // End of variables declaration//GEN-END:variables
    ArrayList<Astronautas> a = new ArrayList();
}
